# Generated by Django 4.2.18 on 2025-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_event_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_latitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_longitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_latitude',
            field=models.DecimalField(decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_longitude',
            field=models.DecimalField(decimal_places=50, max_digits=100, null=True),
        ),
    ]
