# Generated by Django 4.2.18 on 2025-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_moderate_content', 'Can moderate community content'), ('can_manage_events', 'Can manage all events'), ('can_ban_users', 'Can ban users from the community')]},
        ),
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
