# Generated by Django 4.2.18 on 2025-01-24 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_event_is_reported_event_report_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='community.event')),
            ],
            options={
                'db_table': 'event_announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
