# Generated by Django 5.1.5 on 2025-01-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_task_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Messeges',
        ),
    ]
