# Generated by Django 5.1.5 on 2025-01-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_task_messeges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messeges',
            new_name='Messages',
        ),
    ]
