# Generated by Django 5.1.4 on 2025-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_messeges_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
